version: '3'

services:
  postgres:
    container_name: postgres-books-store
    image: postgres
    environment:
      POSTGRES_DB: "books_store"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
    postgres: